# üëçüëé Scan the mood, score the news

You cannot read all the news. It's simply not possible. 
So, let's try to give the job to a machine that will scan the mood.

What you will get here is global average core of that goes from -1 (negative) to 1 (positive). 
This is called natural language processing. 

<br>

üëâ The question is : does "bad" or "negative" means I don't have to invest ?

Usage : 
- secret feature for api key : naas_drivers.cityfalcon.connect("API_KEY") 
- city falcon driver :

In [2]:
import pandas as pd

data = pd.read_json("http://newsapi.org/v2/everything?q=apple&from=2020-10-27&to=2020-10-27&sortBy=popularity&apiKey=c106ee71dca64c8ab968dcccb0a3b5da")

   status  totalResults                                           articles
0      ok          3190  {'source': {'id': None, 'name': 'Lifehacker.co...
1      ok          3190  {'source': {'id': 'engadget', 'name': 'Engadge...
2      ok          3190  {'source': {'id': 'engadget', 'name': 'Engadge...
3      ok          3190  {'source': {'id': 'engadget', 'name': 'Engadge...
4      ok          3190  {'source': {'id': 'engadget', 'name': 'Engadge...
5      ok          3190  {'source': {'id': 'techcrunch', 'name': 'TechC...
6      ok          3190  {'source': {'id': 'techcrunch', 'name': 'TechC...
7      ok          3190  {'source': {'id': 'techcrunch', 'name': 'TechC...
8      ok          3190  {'source': {'id': 'techcrunch', 'name': 'TechC...
9      ok          3190  {'source': {'id': None, 'name': 'Gizmodo.com'}...
10     ok          3190  {'source': {'id': None, 'name': 'Gizmodo.com'}...
11     ok          3190  {'source': {'id': 'mashable', 'name': 'Mashabl...
12     ok          3190  {'source': {'id': 'mashable', 'name': 'Mashabl...
13     ok          3190  {'source': {'id': 'ars-technica', 'name': 'Ars...
14     ok          3190  {'source': {'id': 'ars-technica', 'name': 'Ars...
15     ok          3190  {'source': {'id': None, 'name': 'Blog.google'}...
16     ok          3190  {'source': {'id': 'reuters', 'name': 'Reuters'...
17     ok          3190  {'source': {'id': 'reuters', 'name': 'Reuters'...
18     ok          3190  {'source': {'id': 'reuters', 'name': 'Reuters'...
19     ok          3190  {'source': {'id': 'reuters', 'name': 'Reuters'...